// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFpG7d7zPCfG98zOgHPPdzS_76sAzOKW0',
    appId: '1:528624383851:web:fcca7149d3cfcd30253e2e',
    messagingSenderId: '528624383851',
    projectId: 'fws-dashboard-produccion',
    authDomain: 'fws-dashboard-produccion.firebaseapp.com',
    storageBucket: 'fws-dashboard-produccion.firebasestorage.app',
    measurementId: 'G-WZW1Y20VPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbM1iamfMFQWkr4I9ihjzvu3mf7iU4z-U',
    appId: '1:528624383851:android:e7cdfb9c2135b095253e2e',
    messagingSenderId: '528624383851',
    projectId: 'fws-dashboard-produccion',
    storageBucket: 'fws-dashboard-produccion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQNbCC99FItzX337CxPYzevuu4waZkfpg',
    appId: '1:528624383851:ios:494c3625d0b9c9ba253e2e',
    messagingSenderId: '528624383851',
    projectId: 'fws-dashboard-produccion',
    storageBucket: 'fws-dashboard-produccion.firebasestorage.app',
    iosBundleId: 'com.example.kybaXHectornbbForgeYourDestiny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQNbCC99FItzX337CxPYzevuu4waZkfpg',
    appId: '1:528624383851:ios:494c3625d0b9c9ba253e2e',
    messagingSenderId: '528624383851',
    projectId: 'fws-dashboard-produccion',
    storageBucket: 'fws-dashboard-produccion.firebasestorage.app',
    iosBundleId: 'com.example.kybaXHectornbbForgeYourDestiny',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFpG7d7zPCfG98zOgHPPdzS_76sAzOKW0',
    appId: '1:528624383851:web:61c9ed5be03d0baa253e2e',
    messagingSenderId: '528624383851',
    projectId: 'fws-dashboard-produccion',
    authDomain: 'fws-dashboard-produccion.firebaseapp.com',
    storageBucket: 'fws-dashboard-produccion.firebasestorage.app',
    measurementId: 'G-CDPYHLJDKT',
  );
}
